[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_MAP_PROVIDER = "osm"
  VITE_MAP_TILE_URL = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
